### ISSUE TITLE
MenuMorph avoid grayed-out items

### ISSUE THREAD

**Issue by numberpi** [HPI-SWA-Lab/BP2014H1#1]
**Observed:** The current menu morph has a type-to-select-an-entry logic, but instead of really filtering the result list, it just grayes-out the items that dont match.

**Expected:** It should reduce its list of results.

![capture](https://cloud.githubusercontent.com/assets/4451364/5739515/a6276118-9bfa-11e4-9e9e-39882afc7f79.PNG)

**Comment by leoselig** [comment]
Irrelevant as of #5 
Closed
