### ISSUE TITLE
Undo/Redo Actions for text input

### ISSUE THREAD

**Issue by leoselig** [HPI-SWA-Lab/BP2014H1#4]
Think about implementing this in Paragraph to make it available for all components

Implementation Concept:
- KeyboardEvents are mapped to text commands (pattern)
- text commands can be grouped (e.g. a-z insertions are grouped together to simplify un-/redoing)

**Comment by marceltaeumel** [comment]
Life-times of TextEditor and Paragraph instances are quite short. Keyboard focus changes might cause reinitialization and data loss. See `TextMorph >> #releaseParagraph`.

Also take a look at the current "implementation" of this undo feature in TextEditor -- all Undo\* class variables.

I think, the undo history should be stored in the morph extension of text morphs. Here a code sketch:

``` Smalltalk
TextEditor >> undo
   (self morph valueOfProperty: #undoHistory) last undo.
```

What a coincidence, we just talked about this at lunch. :)

**Comment by leoselig** [comment]
Good to know!
So implementing a solution that works not only for Morphic but for other UI libraries as well won't work?

**Comment by marceltaeumel** [comment]
You mean MVC? I don't care. :) And all other UI Libraries should build on top of Morphic or be something totally different, thus we cannot and should not forsee. ;)

**Comment by marceltaeumel** [comment]
Here is a nice overview of most text editing classes. The interesting part is the ist of class and inst vars with **example objects**. I just looked for `#someInstance` or sub-class instances. No special tracing involved. Yes, it is advertisement for Vivide. :smile: 

If the example object is **nil** this could mean that no instance needs it (at the moment). I try finding non-nil values for 20 instances. Then I give up. For performance reasons.

![into-text-editing](https://cloud.githubusercontent.com/assets/5765308/5742084/d2c046ee-9c0f-11e4-8243-ee150e18c4ea.png)

**Comment by leoselig** [comment]
Closed, not feasable
