### ISSUE TITLE
Generic Eventhandling for Morphs

### ISSUE THREAD

**Issue by numberpi** [HPI-SWA-Lab/BP2014H1#40]
Something like

morph on: aSelector do: aBlock
morph emit: #clicked

**Comment by numberpi** [comment]
Implementation via WeakKeyDictionary did not work as expected.

See BPAnnotatedSuggestionMorph>>cleanUpBPMorphicEventHandler

**Comment by leoselig** [comment]
https://github.com/HPI-SWA-Lab/BP2014H1/commit/ae75fff0a968e0ca425b0daabd8d282634ea4bd1
